spring:
  output:
    ansi:
      enabled: always
  r2dbc:
    username: user
    password: password
    url: r2dbc:mysql://127.0.0.1:3306/database
  main:
    web-application-type: none
  liquibase:
    change-log: classpath*:/db/migrations/changelog-master.xml
    #driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    #daggerok: trace
    io.netty.resolver.dns.DnsServerAddressStreamProviders: off
