spring:
  output:
    ansi:
      enabled: always
  r2dbc:
    username: user
    password: password
    url: r2dbc:mysql://127.0.0.1:3306/database
  main:
    web-application-type: none
  sql:
    init:
      schema-locations: classpath*:/db/migrations/*.ddl.sql
      data-locations: classpath*:/db/migrations/*.dml.sql
      mode: always
logging:
  level:
    io.netty.resolver.dns.DnsServerAddressStreamProviders: off
